Button text component
nwplus/Aurora pull request #45
Opened 2022-06-23 02:33 UTC by meleongg

Closes #39 hopefully, not sure if I did what was expected

2022-06-25 03:36 UTC, samanthatuhseng commented
I feel like the hovers should be states instead of like a toggle?

2022-07-11 07:33 UTC, meleongg commented
Couple of Questions:

1. Should I create a new "Small Button" template in Button.stories.jsx with the associated JS (in Button.js) and CSS (in ButtonCSS.js) since these 2 text components are the same size as the Small Buttons in the Figma file. Currently using the LargeButton template. 

2. I made the font size of my buttons to be 1.1250rem, the equivalent of 18 px (as indicated on Figma file), which is currently larger than the Large button, so not sure if that's what we wanted.

2022-07-11 12:33 UTC, naijwu commented
1. It would make sense to but @ajo01 what do you think of this?
2. I think the font size should be 1.125 rem / 18 px, will need to change the LargeButton font size

2022-07-12 00:46 UTC, ajo01 commented
1. Creating another template would create another component folder in storybook. Ideally we'd keep the current template but rename it to Button and make its size controllable by its props instead (the logic for this currently doesn't exist though). Currently the Button component is a LargeButton component that is actually using some of SmallButton styles. For this PR we should aim to refactor it so the Button component is imported/exported as a Button component, and we can optionally fix the LargeButton/SmallButton styles in another PR. This way the Header component will compile too.
I'll send you a diff patch for this. 
2. We should follow the figma files when possible. You'd be right to use 1.125 rem for the font size. Just make sure to update the font sizes for all the other button styles. 
@phoenixthefirebird FYI

2022-07-13 03:27 UTC, ajo01 requested changes
Looking at the other button components (button nav & pill button), it seems like the people responsible for them will make them separate UI components. Following that, we should make changes so the button text component is its own component with its own ButtonText.js and stories file. Look at Derek's PR for reference https://github.com/nwplus/Aurora/pull/49

2022-07-13 03:27 UTC, ajo01 commented on src/components/button/Button.js
> +
Add `cursor: default` to inactiveText

2022-07-13 18:26 UTC, meleongg commented
<img width="709" alt="Screen Shot 2022-07-13 at 11 16 55 AM" src="https://user-images.githubusercontent.com/62491197/178804564-fb9e2131-e45f-4e8c-b686-9d2ad1837421.png">
<img width="685" alt="Screen Shot 2022-07-13 at 11 17 07 AM" src="https://user-images.githubusercontent.com/62491197/178804589-8c10449b-6f6a-44ce-91f0-4e31e616c8da.png">

NOTE: made background darker via chrome devtools to actually see the button

2022-07-13 20:49 UTC, ajo01 approved these changes
LGTM!

2022-07-13 20:50 UTC, merged